#!/usr/bin/env python

import subprocess
import os

import json

process = subprocess.Popen(["get-location", "-f", "json"], stdout=subprocess.PIPE)
exit_code = os.waitpid(process.pid, 0)
output = process.communicate()[0]
print "OUTPUT: " + output

if output:
    try:
        location = json.loads(output)
    except:
        print "location failed, using default"
        location = '{ "type": "Point", "coordinates": [ 53.80156633, -1.54636951 ] }'

print "location: " + str(location)
